<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1140,"Tablet":""},"elementId":"guten-P6sVWZ","background":{"type":"default","image":{"Desktop":{"id":1136,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/architecture-house-home-pool-ceiling-italy-599832-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"},"repeat":{"Desktop":"no-repeat"},"yposition":{"Desktop":{"point":"","unit":"px"}},"xposition":{"Desktop":{"point":"","unit":"px"}},"videoPlayOnMobile":false,"fetchPriorityHigh":true},"backgroundOverlay":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0.8},"gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":3,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","id":7,"offset":"0.107","active":false},{"color":"rgba(255, 255, 255, 0)","active":true,"id":6,"offset":"0.190"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":5,"offset":"0.293"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":4,"offset":"0.937"}],"gradientType":"linear","gradientAngle":270,"image":{"Desktop":{"id":1119,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/line.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"contain"}},"opacity":"","margin":{"Desktop":{"unit":"px","dimension":{"top":"-150","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"370","bottom":"300","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"243","bottom":"143","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":"120"}}},"zIndex":{"Desktop":"1"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-91Fk0O","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-XvGz0E","content":"Interior designs","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"intrace-accent"},"typography":{"type":"variable","id":"h1-home-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"72"},"Tablet":{"unit":"px","point":"56"},"Mobile":{"unit":"px","point":"29"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.1","Mobile":"0.03"},"transform":"uppercase","weight":"600"},"containsAnchorTag":false,"background":{"type":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":null}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-19Eyfa","content":"from the future","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"h1-home-alt-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"56"},"Tablet":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"28"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.1","Mobile":"0.03"},"transform":"uppercase","weight":"600"},"containsAnchorTag":false,"background":{"type":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":null}} /-->

<!-- wp:gutenverse/button {"elementId":"guten-BTgZlT","content":"View Portfolio","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"18","right":"32","bottom":"18","left":"32"}}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"white"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"width":"1","type":"solid","color":{"type":"variable","id":"white"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"white"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":null},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-hero-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"400"},"hoverTextColor":{"type":"variable","id":"intrace-primary"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
