<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Fun Fact', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"elementId":"guten-vtuMLQ","margin":{"Desktop":{"unit":"px","dimension":{"top":"380","bottom":"0"}},"Tablet":{"unit":"%","dimension":{"top":"55","bottom":"0","right":"0","left":"0"}},"Mobile":{"unit":"%","dimension":{"top":"120","right":"","bottom":"0","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"10","left":"10","bottom":"60"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}}},"zIndex":{"Mobile":""},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-TVlAqf","animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<!-- wp:gutenverse/section {"isChild":true,"elementId":"guten-RPuez5","margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"elementId":"guten-BEmmqp","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/fun-fact {"elementId":"guten-4SGq63","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"prefix":"","number":"25","safeNumber":"25","suffix":"+","title":"Years of Experience","numberColor":{"Desktop":{"type":"variable","id":"intrace-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"numberTypography":{"type":"variable","id":"funfact-number-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"600"},"titleTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"numberBottomSpace":{"Desktop":""},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":[],"Mobile":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"},"imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"elementId":"guten-VVUBqb"} -->
<!-- wp:gutenverse/fun-fact {"elementId":"guten-MHS0qu","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"prefix":"","number":"1250","safeNumber":"1250","suffix":"+","numberFormat":"comma","title":"Projects Completed","numberColor":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"gv-color-text-secondary"}},"numberTypography":{"type":"variable","id":"gv-font-funfact-number-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"600"},"titleTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"numberBottomSpace":{"Desktop":""},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":"4"},"contentPadding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"},"imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"elementId":"guten-sXdd21"} -->
<!-- wp:gutenverse/fun-fact {"elementId":"guten-swuTCt","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"prefix":"","number":"45","safeNumber":"45","suffix":"+","title":"Awwards Winning","numberColor":{"Desktop":{"type":"variable","id":"intrace-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"numberTypography":{"type":"variable","id":"funfact-number-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"600"},"titleTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"numberBottomSpace":{"Desktop":""},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"},"imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"elementId":"guten-n4dsqr","margin":{"Mobile":[]},"padding":{"Mobile":[]},"zIndex":{"Mobile":""}} -->
<!-- wp:gutenverse/fun-fact {"elementId":"guten-OvX2Hw","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"prefix":"","number":"35","safeNumber":"35","suffix":"+","title":"Professional Team","numberColor":{"Desktop":{"type":"variable","id":"intrace-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"intrace-body-text"}},"numberTypography":{"type":"variable","id":"funfact-number-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"600"},"titleTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"numberBottomSpace":{"Desktop":""},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"},"imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-v4QA1y","margin":{"Desktop":{"unit":"px","dimension":{"top":"-100","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","left":"","bottom":""}}},"hideMobile":true} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-tUTHh9","margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"0"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-WBqD4v","content":"achievement","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"accent-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"98"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"containsAnchorTag":false,"textShadow":{"horizontal":"0","vertical":"0","blur":"1","color":{"r":1,"g":1,"b":1,"a":0.3}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Desktop":[],"Tablet":[]},"zIndex":{"Mobile":"0","Desktop":""},"animation":{"type":{"Desktop":"fadeIn"},"duration":"normal","delay":"400"},"hideTablet":false,"hideMobile":true,"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"","unit":"px"}},"positioningAlign":{"Desktop":"flex-start"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"-5","unit":"px"}},"positioningRight":{"Desktop":{"point":"5","unit":"px"}},"positioningTop":{"Desktop":{"point":"-49","unit":"px"}},"positioningBottom":{"Desktop":{"point":"","unit":"px"}}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
