<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Services 2', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-LiIccz","background":{"type":"default","image":{"Desktop":{"id":1138,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/floor-window-home-cottage-property-living-room-1067234-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"intrace-primary"},"image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"opacity":"0.8","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","left":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"60","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"40","left":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-Ialf0C","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-Ke9iES","content":"Services","type":4,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"intrace-accent"},"typography":{"type":"variable","id":"h5-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":{"Desktop":"0.1"},"transform":"uppercase","weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-4A07LX","content":"What We Offer","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"42"},"Tablet":{"unit":"px","point":"34"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-5OxMWD","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","left":"","bottom":"20"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"26","left":"26"}},"Tablet":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"10","left":"10"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-eRbm4I","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"-279"}},"Tablet":{"unit":"px","dimension":{"bottom":"-434","top":"30"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"zIndex":{"Desktop":""},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-qEe47H","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","left":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<!-- wp:gutenverse/image-box {"elementId":"guten-LTfvmA","title":"Residential Design","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore","image":{"media":{"imageId":37,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/villa-house-chair-interior-view-home-1210556-pxhere.com_.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/villa-house-chair-interior-view-home-1210556-pxhere.com_.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/villa-house-chair-interior-view-home-1210556-pxhere.com_.webp","height":490,"width":734,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"villa house chair interior view home","imagePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"imageMargin":{"Desktop":[]},"imageHeight":{"Desktop":{"point":"235","unit":"px"},"Tablet":{"point":"150","unit":"px"},"Mobile":{"point":"200","unit":"px"}},"imageHoverScale":{"Desktop":"1.1"},"bodyBackground":{"type":"default","color":{"type":"variable","id":"white"}},"containerBorder":{"radius":{"Desktop":[],"Mobile":[]}},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"35","bottom":"40","right":"30","left":"30"}},"Mobile":[]},"containerMargin":{"Desktop":[]},"containerBoxShadow":{"color":{"r":1,"g":1,"b":1,"a":0.1},"horizontal":"0","vertical":"5","blur":"15","spread":"0"},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"16","left":"0"}},"Mobile":[],"Tablet":[]},"titleTypography":{"type":"variable","id":"h3-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"titleNormalColor":{"type":"variable","id":"intrace-primary"},"descriptionMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"30","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"50","left":"0"}}},"descriptionTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"descriptionNormalColor":{"type":"variable","id":"intrace-body-text"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"hasInnerBlocks":true,"imageLoad":"lazy"} -->
<!-- wp:gutenverse/button {"elementId":"guten-bNqxKf","content":"Learn more","alignButton":{"Desktop":"center","Tablet":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"32","bottom":"18","left":"32"}},"Tablet":{"unit":"px","dimension":{"top":"18","right":"32","bottom":"18","left":"32"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"intrace-primary"}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"buttonBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":[]},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"400"},"hoverTextColor":{"type":"variable","id":"intrace-primary"},"ariaLabel":"Service Learn More Button"} /-->
<!-- /wp:gutenverse/image-box -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-muDmaw","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<!-- wp:gutenverse/image-box {"elementId":"guten-beVQ6l","title":"Corporate Design","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore","image":{"media":{"imageId":38,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/desk-working-technology-ceiling-yacht-sitting-735699-pxhere.com_.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/desk-working-technology-ceiling-yacht-sitting-735699-pxhere.com_.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/desk-working-technology-ceiling-yacht-sitting-735699-pxhere.com_.webp","height":490,"width":734,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"desk working technology ceiling yacht sitting","imagePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"imageMargin":{"Desktop":[]},"imageHeight":{"Desktop":{"point":"235","unit":"px"},"Tablet":{"point":"150","unit":"px"},"Mobile":{"point":"200","unit":"px"}},"imageHoverScale":{"Desktop":"1.1"},"bodyBackground":{"type":"default","color":{"type":"variable","id":"white"}},"containerBorder":{"radius":{"Desktop":[],"Mobile":[]}},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"35","bottom":"40","right":"30","left":"30"}},"Mobile":[]},"containerMargin":{"Desktop":[]},"containerBoxShadow":{"color":{"r":1,"g":1,"b":1,"a":0.1},"horizontal":"0","vertical":"5","blur":"15","spread":"0"},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"16","left":"0"}},"Mobile":[]},"titleTypography":{"type":"variable","id":"h3-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"titleNormalColor":{"type":"variable","id":"intrace-primary"},"descriptionMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"30","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"50","left":"0"}}},"descriptionTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"descriptionNormalColor":{"type":"variable","id":"intrace-body-text"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"hasInnerBlocks":true,"imageLoad":"lazy"} -->
<!-- wp:gutenverse/button {"elementId":"guten-2G7tKJ","content":"Learn more","alignButton":{"Desktop":"center","Tablet":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"32","bottom":"18","left":"32"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"intrace-primary"}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"buttonBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":[]},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"400"},"hoverTextColor":{"type":"variable","id":"intrace-primary"},"ariaLabel":"Service Learn More Button"} /-->
<!-- /wp:gutenverse/image-box -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-90LKqC","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<!-- wp:gutenverse/image-box {"elementId":"guten-bENWED","title":"Restaurant Design","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore","image":{"media":{"imageId":39,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/cafe-restaurant-bar-meal-interior-design-hotel-691358-pxhere.com_.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/cafe-restaurant-bar-meal-interior-design-hotel-691358-pxhere.com_.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/cafe-restaurant-bar-meal-interior-design-hotel-691358-pxhere.com_.webp","height":490,"width":734,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"cafe restaurant bar meal interior design hotel","imagePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"imageMargin":{"Desktop":[]},"imageHeight":{"Desktop":{"point":"235","unit":"px"},"Tablet":{"point":"150","unit":"px"},"Mobile":{"point":"200","unit":"px"}},"imageHoverScale":{"Desktop":"1.1"},"bodyBackground":{"type":"default","color":{"type":"variable","id":"white"}},"containerBorder":{"radius":{"Desktop":[]}},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"35","bottom":"40","right":"30","left":"30"}}},"containerBoxShadow":{"color":{"r":1,"g":1,"b":1,"a":0.1},"horizontal":"0","vertical":"5","blur":"15","spread":"0"},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"16","left":"0"}},"Mobile":[]},"titleTypography":{"type":"variable","id":"h3-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"titleNormalColor":{"type":"variable","id":"intrace-primary"},"descriptionMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"30","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"50","left":"0"}}},"descriptionTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"descriptionNormalColor":{"type":"variable","id":"intrace-body-text"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"zIndex":{"Mobile":"1"},"hasInnerBlocks":true,"imageLoad":"lazy"} -->
<!-- wp:gutenverse/button {"elementId":"guten-ziyckB","content":"Learn more","alignButton":{"Desktop":"center","Tablet":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"32","bottom":"18","left":"32"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}},"Tablet":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"intrace-primary"}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":[]},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"400"},"hoverTextColor":{"type":"variable","id":"intrace-primary"},"ariaLabel":"Service Learn More Button"} /-->
<!-- /wp:gutenverse/image-box -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
