<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse 404 Hero', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-9rsSZi","background":{"type":"default","image":{"Desktop":{"id":148,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/architecture-house-home-pool-ceiling-italy-599832-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":3,"g":3,"b":3,"a":0.8},"image":{"Desktop":{"id":1119,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/line.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"contain"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-150"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"300","bottom":"300","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"220","bottom":"120","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"200","bottom":"100","right":"10","left":"10"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-vhOgUa","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-YBdzK0","content":"404","type":4,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"intrace-accent"},"typography":{"type":"variable","id":"gv-font-heading-404","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"163"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":""},"font":{"label":"Lato","value":"Lato","type":"google"}},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-mB3J5Q","content":"Page Not Found","type":4,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"42"},"Tablet":{"unit":"px","point":"34"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"50","top":"-10","right":"","left":""}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[]}} /-->

<!-- wp:gutenverse/button {"elementId":"guten-BTgZlT","content":"Back to Home","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"18","right":"32","bottom":"18","left":"32"}}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-white"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"width":"1","type":"solid","color":{"type":"variable","id":"gv-color-white"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-white"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal","delay":"300"},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"400"},"hoverTextColor":{"type":"variable","id":"gv-color-primary"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
