<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Feature', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"elementId":"guten-yBgxvB","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"20","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"0","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"0","right":"10","left":"10"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-5gqsNk"} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-HdPwwy"} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-Ckc137","animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-9Vi7uc","content":"Our Expertise","type":4,"textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"intrace-accent"},"typography":{"type":"variable","id":"h5-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":{"Desktop":"0.1"},"transform":"uppercase","weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-O8FzHx","content":"25 Years of Experience in Interior Design","textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"intrace-primary"},"typography":{"type":"variable","id":"h2-alt-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"300"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-AVExXK","alignment":{"Mobile":"center"},"textColor":{"type":"variable","id":"intrace-body-text"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"60","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"600"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-nl32zf","margin":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"500"}} -->
<!-- wp:gutenverse/progress-bar {"elementId":"guten-6eGKd8","title":"Residential Design","percentage":86,"barColor":{"type":"variable","id":"intrace-border-2"},"trackColor":{"type":"variable","id":"intrace-accent"},"trackHeight":{"Desktop":"15","Mobile":""},"barRadius":{"Desktop":[],"Mobile":[],"Tablet":[]},"trackRadius":{"Desktop":[],"Mobile":[],"Tablet":[]},"barPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"barMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[],"Tablet":[]},"titleColor":{"type":"variable","id":"intrace-primary"},"titleTypography":{"type":"variable","id":"body-font-hero","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"percentColor":{"type":"variable","id":"intrace-primary"},"percentTypography":{"type":"variable","id":"body-font-hero","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} /-->

<!-- wp:gutenverse/progress-bar {"elementId":"guten-wsqyib","title":"Commercial Design","barColor":{"type":"variable","id":"intrace-border-2"},"trackColor":{"type":"variable","id":"intrace-accent"},"trackHeight":{"Desktop":"15"},"barRadius":{"Desktop":[]},"trackRadius":{"Desktop":[]},"barPadding":{"Desktop":[]},"barMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"titleColor":{"type":"variable","id":"intrace-primary"},"titleTypography":{"type":"variable","id":"body-font-hero","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"percentColor":{"type":"variable","id":"intrace-primary"},"percentTypography":{"type":"variable","id":"body-font-hero","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"}} /-->

<!-- wp:gutenverse/progress-bar {"elementId":"guten-yGVfFg","title":"Corporate Design","percentage":78,"barColor":{"type":"variable","id":"intrace-border-2"},"trackColor":{"type":"variable","id":"intrace-accent"},"trackHeight":{"Desktop":"15"},"barRadius":{"Desktop":[]},"trackRadius":{"Desktop":[]},"barPadding":{"Desktop":[]},"barMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"titleColor":{"type":"variable","id":"intrace-primary"},"titleTypography":{"type":"variable","id":"body-font-hero","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"percentColor":{"type":"variable","id":"intrace-primary"},"percentTypography":{"type":"variable","id":"body-font-hero","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
