<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Footer', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1140,"Tablet":""},"gap":"no","elementId":"guten-2komDN","verticalAlign":"flex-start","background":{"type":"default","color":{"type":"variable","id":"gv-color-white"},"videoPlayOnMobile":false},"topDivider":{"type":"mountains","width":{"Desktop":"125","Tablet":"168","Mobile":"245"},"height":{"Desktop":"115","Tablet":"102","Mobile":"91"},"color":{"r":255,"g":255,"b":255,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","bottom":"20","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"20","left":"0","right":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"sectionVerticalAlign":"flex-start","elementId":"guten-ny22d0","margin":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}}}} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-KdsATQ","margin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"","bottom":"0","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":33.596,"Tablet":50,"Mobile":null},"elementId":"guten-tesLDN","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"25","bottom":"0","right":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":{"unit":"px","dimension":{"top":"10","right":"60","bottom":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"60","bottom":"10","left":"10"}}}} -->
<!-- wp:gutenverse/image {"elementId":"guten-eF8OnL","imgSrc":{"media":{"imageId":60,"sizes":{"thumbnail":{"height":86,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/Logo-Black.webp","orientation":"landscape"},"medium":{"height":71,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/Logo-Black.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/Logo-Black.webp","height":86,"width":364,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"Logo Black","captionOriginal":"","width":{"Desktop":{"unit":"%","point":"58"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[]}},"align":{"Desktop":"left"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":[]},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-DrrAQb","alignment":{"Desktop":"left","Tablet":"left","Mobile":"left"},"textColor":{"type":"variable","id":"gv-color-text-secondary-ii"},"typography":{"type":"variable","id":"gv-font-text-ii-ii","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"6"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"","left":"","top":"","bottom":""}},"Tablet":[]}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/social-icons {"elementId":"guten-xQ8gj8","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"14","Tablet":"10","Mobile":"10"},"alignment":{"Desktop":"flex-start","Tablet":"flex-start","Mobile":"flex-start"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"gv-color-white"},"bgColor":{"type":"variable","id":"gv-color-primary"},"iconBorder":{"radius":{"Desktop":[]}},"border":{"radius":{"Desktop":{"unit":"px"}}},"itemPadding":{"unit":"px","Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"hoverIconColor":{"type":"variable","id":"gv-color-white"},"hoverBgColor":{"type":"variable","id":"gv-color-accent"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":{"unit":"px"},"Tablet":[]}} -->
<!-- wp:gutenverse/social-icon {"elementId":"guten-NdXvcs","url":"#","ariaLabel":"Follow us on Facebook","icon":"fab fa-facebook-f","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMjAgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTgwIDI5OS4zVjUxMkgxOTZWMjk5LjNoODYuNWwxOC05Ny44SDE5NlYxNjYuOWMwLTUxLjcgMjAuMy03MS41IDcyLjctNzEuNWMxNi4zIDAgMjkuNCAuNCAzNyAxLjJWNy45QzI5MS40IDQgMjU2LjQgMCAyMzYuMiAwQzEyOS4zIDAgODAgNTAuNSA4MCAxNTkuNHY0Mi4xSDE0djk3LjhIODB6Ii8+PC9zdmc+","text":"","border":{"radius":{"Desktop":[]}},"iconSize":{"Desktop":{"point":"14","unit":"px"}}} /-->

<!-- wp:gutenverse/social-icon {"elementId":"guten-IZAd74","url":"#","ariaLabel":"Follow us on Twitter","icon":"fab fa-x-twitter","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTM4OS4yIDQ4aDcwLjZMMzA1LjYgMjI0LjIgNDg3IDQ2NEgzNDVMMjMzLjcgMzE4LjYgMTA2LjUgNDY0SDM1LjhMMjAwLjcgMjc1LjUgMjYuOCA0OEgxNzIuNEwyNzIuOSAxODAuOSAzODkuMiA0OHpNMzY0LjQgNDIxLjhoMzkuMUwxNTEuMSA4OGgtNDJMMzY0LjQgNDIxLjh6Ii8+PC9zdmc+","text":"","iconSize":{"Desktop":{"point":"","unit":"px"}}} /-->

<!-- wp:gutenverse/social-icon {"elementId":"guten-2iRJ2L","url":"#","ariaLabel":"Follow us on Instagram","icon":"fab fa-instagram","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTIyNC4xIDE0MWMtNjMuNiAwLTExNC45IDUxLjMtMTE0LjkgMTE0LjlzNTEuMyAxMTQuOSAxMTQuOSAxMTQuOVMzMzkgMzE5LjUgMzM5IDI1NS45IDI4Ny43IDE0MSAyMjQuMSAxNDF6bTAgMTg5LjZjLTQxLjEgMC03NC43LTMzLjUtNzQuNy03NC43czMzLjUtNzQuNyA3NC43LTc0LjcgNzQuNyAzMy41IDc0LjcgNzQuNy0zMy42IDc0LjctNzQuNyA3NC43em0xNDYuNC0xOTQuM2MwIDE0LjktMTIgMjYuOC0yNi44IDI2LjgtMTQuOSAwLTI2LjgtMTItMjYuOC0yNi44czEyLTI2LjggMjYuOC0yNi44IDI2LjggMTIgMjYuOCAyNi44em03Ni4xIDI3LjJjLTEuNy0zNS45LTkuOS02Ny43LTM2LjItOTMuOS0yNi4yLTI2LjItNTgtMzQuNC05My45LTM2LjItMzctMi4xLTE0Ny45LTIuMS0xODQuOSAwLTM1LjggMS43LTY3LjYgOS45LTkzLjkgMzYuMXMtMzQuNCA1OC0zNi4yIDkzLjljLTIuMSAzNy0yLjEgMTQ3LjkgMCAxODQuOSAxLjcgMzUuOSA5LjkgNjcuNyAzNi4yIDkzLjlzNTggMzQuNCA5My45IDM2LjJjMzcgMi4xIDE0Ny45IDIuMSAxODQuOSAwIDM1LjktMS43IDY3LjctOS45IDkzLjktMzYuMiAyNi4yLTI2LjIgMzQuNC01OCAzNi4yLTkzLjkgMi4xLTM3IDIuMS0xNDcuOCAwLTE4NC44ek0zOTguOCAzODhjLTcuOCAxOS42LTIyLjkgMzQuNy00Mi42IDQyLjYtMjkuNSAxMS43LTk5LjUgOS0xMzIuMSA5cy0xMDIuNyAyLjYtMTMyLjEtOWMtMTkuNi03LjgtMzQuNy0yMi45LTQyLjYtNDIuNi0xMS43LTI5LjUtOS05OS41LTktMTMyLjFzLTIuNi0xMDIuNyA5LTEzMi4xYzcuOC0xOS42IDIyLjktMzQuNyA0Mi42LTQyLjYgMjkuNS0xMS43IDk5LjUtOSAxMzIuMS05czEwMi43LTIuNiAxMzIuMSA5YzE5LjYgNy44IDM0LjcgMjIuOSA0Mi42IDQyLjYgMTEuNyAyOS41IDkgOTkuNSA5IDEzMi4xczIuNyAxMDIuNy05IDEzMi4xeiIvPjwvc3ZnPg==","text":"","iconSize":{"Desktop":{"point":"","unit":"px"}}} /-->

<!-- wp:gutenverse/social-icon {"elementId":"guten-tzjfNS","url":"#","ariaLabel":"Follow us on Linkedin","icon":"fab fa-linkedin-in","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTEwMC4yOCA0NDhINy40VjE0OC45aDkyLjg4ek01My43OSAxMDguMUMyNC4wOSAxMDguMSAwIDgzLjUgMCA1My44YTUzLjc5IDUzLjc5IDAgMCAxIDEwNy41OCAwYzAgMjkuNy0yNC4xIDU0LjMtNTMuNzkgNTQuM3pNNDQ3LjkgNDQ4aC05Mi42OFYzMDIuNGMwLTM0LjctLjctNzkuMi00OC4yOS03OS4yLTQ4LjI5IDAtNTUuNjkgMzcuNy01NS42OSA3Ni43VjQ0OGgtOTIuNzhWMTQ4LjloODkuMDh2NDAuOGgxLjNjMTIuNC0yMy41IDQyLjY5LTQ4LjMgODcuODgtNDguMyA5NCAwIDExMS4yOCA2MS45IDExMS4yOCAxNDIuM1Y0NDh6Ii8+PC9zdmc+","text":"","iconSize":{"Desktop":{"point":"","unit":"px"}}} /-->
<!-- /wp:gutenverse/social-icons -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":17.193,"Tablet":50,"Mobile":null},"elementId":"guten-twyPW9","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px"},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"10","top":"10","right":"10","bottom":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"10","bottom":"10","left":"10"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-sO3d36","content":"Other Pages","type":3,"color":{"type":"variable","id":"gv-color-primary-ii"},"typography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"20","left":""}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/icon-list {"elementId":"guten-i6IA0S","spaceBetween":{"Desktop":"10","Tablet":"6"},"iconColor":{"type":"variable","id":"gv-color-text-secondary"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"textColorHover":{"type":"variable","id":"gv-color-accent"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px"}}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-eQhJYV","url":"#","hasGlobalLink":true,"hideIcon":true,"text":"Home"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-GoLOd5","url":"#","hasGlobalLink":true,"hideIcon":true,"text":"About Us","margin":{"Mobile":[]},"padding":{"Mobile":[]}} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-FdyBkN","url":"#","hasGlobalLink":true,"hideIcon":true,"text":"Services"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-7e8WIC","url":"#","hasGlobalLink":true,"hideIcon":true,"text":"Contact"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-Nvf4Am","url":"#","hasGlobalLink":true,"hideIcon":true,"text":"Project"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":14.211,"Tablet":50,"Mobile":null},"elementId":"guten-LeU3u2","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"10","top":"10","right":"10","bottom":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"10","bottom":"10","left":"10"}},"Tablet":[]}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-uaN082","content":"Quick Links","type":3,"color":{"type":"variable","id":"gv-color-primary-ii"},"typography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"20","left":""}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/icon-list {"elementId":"guten-xS3zIx","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"gv-color-text-secondary"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"textColorHover":{"type":"variable","id":"gv-color-accent"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px"}}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-G5yfDe","url":"#","hasGlobalLink":true,"hideIcon":true,"text":"Privacy Policy"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-hf48dp","url":"#","hasGlobalLink":true,"hideIcon":true,"text":"Term Of Service","margin":{"Mobile":[]},"padding":{"Mobile":[]}} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-eAZiIP","url":"#","hasGlobalLink":true,"hideIcon":true,"text":"Disclaimer"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-bAMM57","url":"#","hasGlobalLink":true,"hideIcon":true,"text":"Credits"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-kcPVoD","url":"#","hasGlobalLink":true,"hideIcon":true,"text":"FAQ"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":35,"Tablet":50},"elementId":"guten-RAssi1","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"30"}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"10","top":"10","right":"10","bottom":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-qAjwcF","content":"Latest Projects","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-primary-ii"},"typography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"5"}}}} /-->

<!-- wp:gutenverse/gallery {"elementId":"guten-YfB2NC","zoomIcon":"","linkIcon":"","column":{"Desktop":"3","Tablet":"2"},"height":{"Desktop":"70"},"images":[{"id":"One","_key":"Wc3hhY","src":{"id":222,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/architecture-house-floor-interior-home-ceiling-1204487-pxhere.com_.webp"},"link":"#","imageLoad":"eager"},{"id":"Two","_key":"vRlxwC","src":{"id":223,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/floor-home-cottage-kitchen-property-living-room-1389997-pxhere.com_.webp"},"link":"#","imageLoad":"eager"},{"id":"Three","_key":"UaSt1t","src":{"id":224,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/interior-home-ceiling-workspace-loft-property-1392243-pxhere.com_.webp"},"link":"#","imageLoad":"eager"},{"id":"Four","_key":"cNETip","src":{"id":225,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/floor-interior-home-ceiling-loft-office-1390062-pxhere.com_.webp"},"link":"#","imageLoad":"eager","imageAlt":"original"},{"id":"Five","_key":"YQxdaS","src":{"id":227,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/komfort-kreative-loveseat-interier-kurort-luxury-1632960-pxhere.com_.webp"},"link":"#","imageLoad":"eager","imageAlt":"original"},{"id":"Six","_key":"8gPcHH","src":{"id":226,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/room-living-room-interior-design-property-furniture-building-1632949-pxhere.com_.webp"},"link":"#","imageLoad":"eager","imageAlt":"original"}],"iconBg":{"r":255,"g":255,"b":255,"a":0.01},"iconPadding":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"itemPadding":{"Desktop":{"unit":"%","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"itemMargin":{"Desktop":{"unit":"%","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}},"Tablet":{"unit":"%","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}},"Mobile":{"unit":"%","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"itemBorder":{"radius":{"Desktop":[],"Tablet":[]}},"itemHoverBackground":{"type":"default","color":{"r":12,"g":12,"b":12,"a":1}},"itemHoverPadding":{"Desktop":[]},"itemHoverBorder":{"radius":{"Desktop":[]}},"filterTabPadding":{"Tablet":[]},"filterTabMargin":{"Tablet":[]},"filterTabBorder":{"radius":{"Tablet":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"titleHeadingType":"h4"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/divider {"elementId":"guten-azjT0Z","width":{"Desktop":"98"},"dividerColor":{"r":160,"g":170,"b":186,"a":0.17},"size":{"Desktop":"1"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"10","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}},"Mobile":[]}} /-->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-dnc1OC","verticalAlign":"center","border":{"radius":{"Desktop":{"unit":"px"}},"top":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":0.1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"","right":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":64},"sectionVerticalAlign":"center","elementId":"guten-xpw1eN","verticalAlign":{"Desktop":"default","Tablet":"default","Mobile":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":"10"}}}} -->
<!-- wp:gutenverse/text-editor {"elementId":"guten-ZVsZIs","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"center","Tablet":"left","Mobile":"center"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":true,"linkColor":{"type":"variable","id":"gv-color-text-primary"},"linkColorHover":{"type":"variable","id":"gv-color-accent"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:paragraph -->
<p>Copyright © 2026. Powered by&nbsp;<a href="https://gutenverse.com/">Intrace</a>&nbsp;Interior Design &amp; Architecture Theme</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
