<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home About 2', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"elementId":"guten-tCOlqI","overflow":"hidden","margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"60","right":"10","left":"10","bottom":"60"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","left":"10","bottom":"40"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-bGOpBl","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"60","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"40","bottom":"10","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"zIndex":{"Desktop":""},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-GqpPRO","content":"Awward Winning","type":3,"textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"intrace-accent"},"typography":{"type":"variable","id":"h5-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":{"Desktop":"0.1"},"transform":"uppercase","weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"10"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-WbIqHf","content":"Interior Design","textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"intrace-primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"42"},"Tablet":{"unit":"px","point":"34"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":{"Desktop":"0.01"},"transform":"uppercase","weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-W5WFOg","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Mobile":"center"},"textColor":{"type":"variable","id":"intrace-body-text"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"6","top":"6","right":"6","left":"6"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit </p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/image {"elementId":"guten-uZoDhW","imgSrc":{"media":{"imageId":20,"sizes":{"thumbnail":{"height":80,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/sign.webp","orientation":"landscape"},"medium":{"height":55,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/sign.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/sign.webp","height":80,"width":440,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"sign","captionOriginal":"","width":{"Desktop":{"unit":"%","point":"45"},"Mobile":{"unit":"%","point":"65"},"Tablet":{"unit":"%","point":"65"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[],"Tablet":[]}},"align":{"Desktop":"left","Mobile":"center"},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"lazyLoad":true,"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-bPA5Bo","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Mobile":"center"},"textColor":{"type":"variable","id":"intrace-primary"},"typography":{"type":"variable","id":"h3-font-secondary","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"5"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
<!-- wp:paragraph -->
<p>Jonathan Doe, CEO</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-CUPXE2","content":"Read more","alignButton":{"Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"32","left":"32"}},"Mobile":[],"Tablet":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"intrace-primary"}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"width":"1","type":"solid","color":{"type":"variable","id":"intrace-primary"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"intrace-primary"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"600"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"button-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"400"},"hoverTextColor":{"type":"variable","id":"intrace-primary"}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-DrUcl9","background":{"type":"default"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":""}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":""},"hideTablet":false,"hideMobile":false} -->
<!-- wp:gutenverse/image {"elementId":"guten-vcyyIJ","imgSrc":{"media":{"imageId":21,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/wood-floor-home-loft-rug-property-943609-pxhere.com_.webp","orientation":"landscape"},"medium":{"height":241,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/wood-floor-home-loft-rug-property-943609-pxhere.com_.webp","orientation":"landscape"},"large":{"height":823,"width":1024,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/wood-floor-home-loft-rug-property-943609-pxhere.com_.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/wood-floor-home-loft-rug-property-943609-pxhere.com_.webp","height":900,"width":1120,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"wood floor home loft rug property","captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"412","unit":"px"},"Tablet":{"point":"265","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"imageFit":{"Desktop":"cover"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"300"},"hideMobile":true,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/section {"isChild":true,"height":{"Desktop":{"point":"160","unit":"px"},"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"}},"gap":"no","elementId":"guten-seeatL","heightControl":"min","margin":{"Desktop":{"unit":"%","dimension":{"top":"-29","left":"-50","bottom":"0","right":"29"}},"Tablet":{"unit":"px","dimension":{"top":"12","right":"-152","left":"-108","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"zIndex":{"Desktop":"3"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-bjtIhv","background":{"type":"default","color":{"type":"variable","id":"white"}},"verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":[]}},"boxShadow":{"horizontal":"0","vertical":"5","blur":"10","spread":"0","color":{"r":1,"g":1,"b":1,"a":0.1}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"","right":"41","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"25","bottom":"25","left":"25"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"25","right":"25","bottom":"25","left":"25"}}},"zIndex":{"Desktop":""},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-qV5cs4","border":{"radius":{"Desktop":[]}},"borderHover":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-aYO2f8","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<!-- wp:gutenverse/text-editor {"elementId":"guten-fsYpaw","gap":{"Desktop":{"point":"","unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"intrace-body-text"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]},"left":{"type":"solid","width":"2","color":{"type":"variable","id":"intrace-accent"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","left":"30","top":"0"}}}} -->
<!-- wp:paragraph -->
<p>“Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore”&nbsp;</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/heading {"elementId":"guten-kgqg8n","content":"Jonathan Doe","type":3,"color":{"type":"variable","id":"intrace-primary"},"typography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
